import { config } from 'dotenv';
config();

import '@/ai/flows/context-aware-tips.ts';
import '@/ai/flows/cyber-intel-flow.ts';
import '@/ai/flows/offensive-tool-flow.ts';
import '@/ai/flows/phishing-flow.ts';
import '@/ai/flows/osint-flow.ts';
import '@/ai/flows/vapt-flow.ts';
import '@/ai/flows/reporting-flow.ts';
import '@/ai/flows/cve-feed-flow.ts';
import '@/ai/flows/law-updates-flow.ts';
import '@/ai/flows/wordlist-generator-flow.ts';
import '@/ai/flows/page-cloner-flow.ts';
import '@/ai/flows/malware-analysis-flow.ts';
import '@/ai/flows/virustotal-scan-flow.ts';
import '@/ai/flows/steganography-flow.ts';
import '@/ai/flows/social-media-analysis-flow.ts';
import '@/ai/flows/password-cracker-flow.ts';
import '@/ai/flows/activity-feed-flow.ts';
import '@/ai/flows/config-analyzer-flow.ts';
import '@/ai/flows/duckyscript-generator-flow.ts';
import '@/ai/flows/exploit-suggester-flow.ts';
import '@/ai/flows/suggest-campaign-tasks-flow.ts';
import '@/ai/flows/phishing-simulation-flow.ts';
import '@/ai/flows/network-analysis-flow.ts';
import '@/ai/flows/threat-actor-flow.ts';
import '@/ai/flows/payload-generator-flow.ts';
import '@/ai/flows/c2-checkin-flow.ts';
import '@/ai/flows/c2-command-flow.ts';
import '@/ai/flows/custom-malware-generator-flow.ts';
import '@/ai/flows/network-topology-flow.ts';
