
import { config } from 'dotenv';
config();

import '@/ai/flows/context-aware-tips.ts';
import '@/ai/flows/cyber-intel-flow.ts';
import '@/ai/flows/phishing-flow.ts';
import '@/ai/flows/vapt-flow.ts';
import '@/ai/flows/reporting-flow.ts';
import '@/ai/flows/malware-analysis-flow.ts';
import '@/ai/flows/steganography-flow.ts';
import '@/ai/flows/social-media-analysis-flow.ts';
import '@/ai/flows/config-analyzer-flow.ts';
import '@/ai/flows/duckyscript-generator-flow.ts';
import '@/ai/flows/exploit-suggester-flow.ts';
import '@/ai/flows/suggest-campaign-tasks-flow.ts';
import '@/ai/flows/network-analysis-flow.ts';
import '@/ai/flows/threat-actor-flow.ts';
import '@/ai/flows/c2-checkin-flow.ts';
import '@/ai/flows/c2-command-flow.ts';
import '@/ai/flows/c2-screenshot-flow.ts';
import '@/ai/flows/custom-malware-generator-flow.ts';
import '@/ai/flows/network-topology-flow.ts';
import '@/ai/flows/yara-rule-generator-flow.ts';
import '@/ai/flows/campaign-planner-flow.ts';
import '@/ai/flows/log-analysis-flow.ts';
import '@/ai/flows/ioc-extractor-flow.ts';
import '@/ai/flows/workflow-summary-flow.ts';
import '@/ai/flows/port-scanner-flow.ts';
import '@/ai/flows/injection-scanner-flow.ts';
import '@/ai/flows/exploit-chain-assistant-flow.ts';
import '@/ai/flows/firmware-analysis-flow.ts';
import '@/ai/flows/iot-traffic-analysis-flow.ts';
import '@/ai/flows/anonymizer-flow.ts';
import '@/ai/flows/generate-telegram-bot-flow.ts';
import '@/ai/flows/document-generator-flow.ts';
import '@/ai/flows/invite-user-flow.ts';
import '@/ai/flows/test-email-flow.ts';
import '@/ai/flows/clone-page-from-url-flow.ts';
import '@/ai/flows/telegram-c2-flow.ts';
