
'use client';

// This page is intentionally left blank. 
// The blob: URL generated by the cloner is handled entirely by the browser
// and does not correspond to a route in the Next.js application.
// This file exists to satisfy the router but will not be rendered when a blob URL is visited.

export default function PhishPage() {
    return null;
}
